# Generated by Django 5.2.8 on 2026-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country_name',
            field=models.CharField(default='Sadiq', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
